id: IBD84BADA
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-17T14:06:15.958924'
last_modified: '2022-06-17T14:06:15.958948'
parser: null
source_metadata:
  title: Seven Branches Series
  language: fr
  description: Texts on the theme of the seven-branch (yan lag bdun pa; saptāṅga)
    service, commonly consisting of 1) prostration/homage, 2) making offerings, 3)
    confession of negative actions, 4) rejoicing in others' virtue, 5) requesting
    the turning of the dharma wheel, 6) imploring teachers to remain and not pass
    into parinirvāṇa, and 7) dedicating merit to the enlightenment of all sentient
    beings.
  volume:
    f341D:
      title: Seven-Branch Offering to Tārā
      base_file: f341D.txt
      order: 1
      parent: Practices
    f70CE:
      title: The Seven Branches for Practising the Sacred Dharma
      base_file: f70CE.txt
      order: 2
      parent: Practices
    f3393:
      title: The Eight-Branch Offering from the Gyüluk Phurba
      base_file: f3393.txt
      order: 3
      parent: Eight Branches
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
